name: 'dispatch-single-icu-single-php-intl'
on:
  workflow_dispatch:
    inputs:
      icu:
        description: ICU version
        required: true
      php:
        description: PHP version
        required: true
      rebuild:
        description: rebuild
        required: false

jobs:
  php-intl:
    container: ${{ matrix.container }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ts: ['zts', 'nts']
        os: [ubuntu-latest, ubuntu-22.04-arm]
        include:
          - os: ubuntu-latest
            container: ubuntu:jammy
          - os: ubuntu-22.04-arm
            container: arm64v8/ubuntu:jammy
    name: php-intl
    steps:
      - name: ${{github.event.inputs.php}}
        id: print_details
        run: |
          echo sender=${{github.event.sender.login}}
          echo ICU=${{github.event.inputs.icu}}
          echo PHP=${{github.event.inputs.php}}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: bash src/install-requirements.sh
        env:
          TS: ${{ matrix.ts }}
          VERSION: ${{ github.event.inputs.php }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update intl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ICU: ${{ github.event.inputs.icu }}
          REPO: ${{ github.repository }}
          TS: ${{ matrix.ts }}
          VERSION: ${{ github.event.inputs.php }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          existing_version=$(gh release view intl-$ICU 2>/dev/null | grep -Po "$VERSION-$ICU" | head -n 1)
          if [ "$VERSION-$ICU" != "$existing_version" ] || [ "x${{github.event.inputs.rebuild}}" = "xtrue" ]; then
            bash src/build-intl.sh
            bash src/release-intl.sh
          else
            echo "intl $VERSION-$ICU build exists"
          fi
